### ISSUE TITLE
Keys command

### ISSUE THREAD

**Issue by ariefdarmawan** [eaciit/mq#10]
Please create keys command

```
keys(nodenumber)
```

to display all keys for respective node mentioned

**Comment by sugab** [comment]
Is it something like this?

![screen shot 2015-06-10 at 4 02 50 pm](https://cloud.githubusercontent.com/assets/6898295/8078861/d487c58a-0f8a-11e5-8e9a-4d4d51ebfb83.png)

Node is running on port 7890
Keys available: public|key1, public|key2 something like that

**Comment by ghost** [comment]
yes .. change keys available to Available keys:  ... and last element should has no comma after it

**Comment by sugab** [comment]
Fixed with this commit [01c7f25](https://github.com/eaciit/mq/commit/01c7f25e3a102b53dc9f167a32813493f02a471d)
