### ISSUE TITLE
Create REST API GetToken

### ISSUE THREAD

**Issue by ariefdarmawan** [eaciit/mq#21]
Proto /api/gettoken?username=xxx&password=yyyy

return  
{data:{token:"32 char tokenkey",valid:datetime},result:"ok",message:"always blank except if there would be error"}

List of token need to be saved and will be used globally
- A token will be generated for valid user, if there is no valid token existed before
- A new created token will have 15 mins validity (or whatever time configured). 
- After exceeds validity - period, token will be invalid and need to be marked as expired and cant be used for further operation.
- When an operation is invoked, a new validity period will be assigned to token. New validity period will be time of execution + validity period

**Comment by sugab** [comment]
sir sorry but i'm a bit confused what is token means...
and should i create new server called mqapi.go or i combine with mqmonitor.go server

**Comment by ghost** [comment]
Create new webapp called as mqapi run on different port

Api/gettoken is the siganture of the api. You should create a routing for that purpose.

Gorilla has bunch of library for this purpose. But if you prefer to do it from the scratch also ok with me :)

*\* sent from phone, apologize should there be typo **

Arief Darmawan
Co-Founder, Product Development
EACIIT - Enhancing Enterprise Value
http://www.eaciit.com
+628118097897
+6597789935

On 17 Jun 2015, at 10.38, Bagus Cahyono <notifications@github.com<mailto:notifications@github.com>> wrote:

sir sorry but i'm a bit confused what is token means...
and should i create new server called mqapi.go or i combine with mqmonitor.go server

##

**Comment by nandabudi** [comment]
Aye sir :D
