### ISSUE TITLE
Create Info

### ISSUE THREAD

**Issue by ariefdarmawan** [eaciit/mq#9]
Please create info command

```
info(keyname)
```

To retrieve info of specific key. ie. value, owner, created, last access and node location

**Comment by sugab** [comment]
info command already added with output:
![screen shot 2015-06-11 at 10 41 59 am](https://cloud.githubusercontent.com/assets/6898295/8099416/ddce1206-1026-11e5-83d6-4afc78363b83.png)

But still using public key. Should i retrieve owner key as well like get command?

**Comment by ghost** [comment]
no need for now. Thx

Thanks & Regards,

Arief Darmawan
EACIIT - Enhance Enterprise Value
+62 811 8097 897

On Jun 11, 2015, at 10:46 AM, Bagus Cahyono <notifications@github.com<mailto:notifications@github.com>> wrote:

info command already added with output:
[screen shot 2015-06-11 at 10 41 59 am]https://cloud.githubusercontent.com/assets/6898295/8099416/ddce1206-1026-11e5-83d6-4afc78363b83.png

But still using public key. Should i retrieve owner key as well like get command?
